schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "NodePie"
version = "1.2.29"
name = "Node Pie"
tagline = "Add nodes visually with a pie menu"
maintainer = "Andrew Stevenson"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional: add-ons can list which resources they will require:
# * "files" (for access of any filesystem operations)
# * "network" (for internet access)
# * "camera" (to capture photos and videos)
# * "microphone" (to capture audio)
permissions = ["files"]

# Optional link to documentation, support, source files, etc
website = "https://github.com/strike-digital/node_pie"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["User Interface", "Node"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = ["SPDX:GPL-2.0-or-later"]
